# action.yml
name: 'sesam-node-diff-github-action'
description: 'Download config from Sesam node and compare with local files'
inputs:
  download:
    description: 'Download config from Sesam node'
    required: true
    default: true
  node:
    description: 'Sesam node url. eg "datahub-asdfasdf.sesam.cloud"'
    required: true
  jwt:
    description: 'JWT authorization token created by the Sesam portal'
    required: true
  config_path_local:
    description: 'the path to the local sesam config folder. E.g. from checkout action.'
    required: true
    default: node
  config_path_download:
    description: 'the path to the downloaded config folder'
    required: true
    default: node_downloaded
  config_group:
    description: 'config-group to place the config in. Defaults to "default"'
    default: 'Default'
    required: true
  git_args:
    description: 'arguments to pass to git diff'
    default: ''
    required: false
outputs:
  status_code: # id of output
    description: 'status code returned by service API'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.git_args}}
